In [3]:
import numpy as np

In [4]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [5]:
#a
corrected_temp = temperature + 2

#b
fahrenheit_temp = (9/5) * corrected_temp + 32

#c
above_32 = corrected_temp[corrected_temp > 32]

#d
count_above_32 = np.sum(corrected_temp > 32)

In [6]:
#q1
print("Original readings (°C):", temperature)
print("Corrected readings (°C):", corrected_temp)
print("Converted readings (°F):", fahrenheit_temp)
print("Readings above 32°C:", above_32)
print("Count above 32°C:", count_above_32)

Original readings (°C): [25 28 31 35 38 27 33 40]
Corrected readings (°C): [27 30 33 37 40 29 35 42]
Converted readings (°F): [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings above 32°C: [33 37 40 35 42]
Count above 32°C: 5


In [7]:
#q2
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [8]:
#a
total_steps = np.sum(steps)

#b
mean_steps = np.mean(steps)

#c
max_steps = np.max(steps)
min_steps = np.min(steps)

#d
daily_totals = np.sum(steps, axis=0)

#e
user_totals = np.sum(steps, axis=1)

#f
max_position = np.unravel_index(np.argmax(steps), steps.shape)

In [9]:
print("Total steps recorded:", total_steps)
print("Mean steps:", mean_steps)
print("Maximum steps:", max_steps)
print("Minimum steps:", min_steps)
print("Total steps per day:", daily_totals)
print("Total steps per user:", user_totals)
print("Position of maximum steps (user, day):", max_position)

Total steps recorded: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps per day: [26500 27300 30400]
Total steps per user: [18300 24500 14400 27000]
Position of maximum steps (user, day): (np.int64(3), np.int64(2))


In [10]:
#Q3
#a
original = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", original)

#b
subset = original[1:5]
print("Subset (slice 1 to 4):", subset)

#c
subset[0] = 999
print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)

#d
copied_subset = original[1:5].copy()
copied_subset[0] = 500
print("After modifying copied subset:")
print("Original:", original)
print("Copied subset:", copied_subset)

#e
matrix = np.arange(1, 13).reshape(3, 4)
print("\n3x4 Matrix:\n", matrix)

#f
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1–2, Columns 2–3:\n", matrix[0:2, 1:3])

#g
flattened = matrix.flatten()
raveled = matrix.ravel()
print("\nFlattened (flatten):", flattened)
print("Raveled (ravel):", raveled)

#h
raveled[0] = 999
print("\nAfter modifying ravel[0]:")
print("Matrix:\n", matrix)
print("Raveled:", raveled)

#i
flattened[0] = 500
print("\nAfter modifying flatten[0]:")
print("Matrix:\n", matrix)
print("Flattened:", flattened)

#j
print("\nMatrix properties:")
print("Shape:", matrix.shape)
print("Dimensions (ndim):", matrix.ndim)
print("Size (total elements):", matrix.size)
print("Data type (dtype):", matrix.dtype)


Original array: [1 2 3 4 5 6]
Subset (slice 1 to 4): [2 3 4 5]
After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
After modifying copied subset:
Original: [  1 999   3   4   5   6]
Copied subset: [500   3   4   5]

3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1–2, Columns 2–3:
 [[2 3]
 [6 7]]

Flattened (flatten): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled (ravel): [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel[0]:
Matrix:
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Raveled: [999   2   3   4   5   6   7   8   9  10  11  12]

After modifying flatten[0]:
Matrix:
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened: [500   2   3   4   5   6   7   8   9  10  11  12]

Matrix properties:
Shape: (3, 4)
Dimensions (ndim): 2
Size (total elements): 12
Data type (dtype): int64


In [10]:
#Q4

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])


y = np.array([40, 65, 30, 85])

#a
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

#b
X_T = X.T
print("\nX.T:\n", X_T)
print("Transpose means rows become columns → features grouped together.")

#c
XT_X = X_T @ X
print("\nX.T @ X:\n", XT_X)

#d
XT_X_inv = np.linalg.inv(XT_X)
print("\nInverse of (X.T @ X):\n", XT_X_inv)

#e
beta = XT_X_inv @ X_T @ y
print("\nOLS Coefficients (β):", beta)

#g
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score for new user:", predicted_score)
