In [21]:
import numpy as np

In [22]:
array = np.array([6, 10, 14, 16, 20])
print("After Adding 2 : ",array+2)

After Adding 2 :  [ 8 12 16 18 22]


In [23]:
print("After Multiplying by 3 : ",array*3)

After Multiplying by 3 :  [18 30 42 48 60]


In [24]:
print("After Dividing by 2 : ",array/2)

After Dividing by 2 :  [ 3.  5.  7.  8. 10.]


In [25]:
#Q2a
arr = np.array([1,2,3,6,4,5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [26]:
#Q2b
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
a,b = np.unique(x, return_counts=True)
elementx = (a[np.argmax(b)])
indexx = np.where(x == elementx)
print("Max occurrence is of : ",elementx)
print("Indices : ",indexx[0])

Max occurrence is of :  1
Indices :  [0 5 7 8 9]


In [27]:
c,d = np.unique(y, return_counts=True)
elementy = (c[np.argmax(d)])
indexy = np.where(y == elementy)
print("Max occurrence is of : ",elementy)
print("Indices : ",indexy[0])


Max occurrence is of :  1
Indices :  [0 1 2]


In [28]:
#Q3a,b
arr3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1st Row 2nd Col : ",arr3[0,1])
print("3rd Row 1st Col : ",arr3[2,0])

1st Row 2nd Col :  20
3rd Row 1st Col :  70


In [29]:
#Q4
akshtprakash = np.linspace(10,100,25)
print("Dimension : ",akshtprakash.ndim)
print("Shape : ",akshtprakash.shape)
print("Total Elements : ",akshtprakash.size)
print("Data Type : ",akshtprakash.dtype)
print("Total Bytes : ",akshtprakash.nbytes)
print("Transpose using reshape :",akshtprakash.reshape(25,1))
print("Transpose using T : ",akshtprakash.T)

Dimension :  1
Shape :  (25,)
Total Elements :  25
Data Type :  float64
Total Bytes :  200
Transpose using reshape : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [30]:
#Q5
ucs420_akshtprakash = np.array([10,20,30,40,50,60,70,80,90,15,20,35])
print("Mean : ",np.mean(ucs420_akshtprakash))
print("Median : ",np.median(ucs420_akshtprakash))
print("Max : ",np.max(ucs420_akshtprakash))
print("Min : ",np.min(ucs420_akshtprakash))
print("Unique : ",np.unique(ucs420_akshtprakash))
reshaped_ucs420_akshtprakash = ucs420_akshtprakash.reshape(4,3)
print("Reshaped : ",reshaped_ucs420_akshtprakash)
resized_ucs420_jatinkalra = np.resize(ucs420_akshtprakash,(2,3))
print("Resized : ",resized_ucs420_akshtprakash)

Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique :  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped :  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


NameError: name 'resized_ucs420_akshtprakash' is not defined